name: Deploy to Server

on:
  push:
    branches:
      - onnes-26  # Adjusted to 'master' as per your current branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Ensure this matches the secret name

      - name: Run deployment script
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@www.onnescryogenics.com.au  << 'EOF' 
            cd /home/ubuntu/Onnes.In
            ./deploy.sh onnes-26  # Using 'master' as the branch name
          EOF
